baseURL = "https://clingm.github.io/"
languageCode = "en-us"
title = "Clingm's Blog"
theme="archie"
copyright = "© Clingm"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableGitInfo = true

# disqusShortname = "yourDisqusShortname"

pagination.pagerSize=6 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	# subtitle = "我的个人blog，写的内容会比较杂。"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	customCSS = ["css/custom.css"] # 引入自定义的css样式
	toc = true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/clingm"


# Main menu Items

[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts"
weight = 2

[[menu.main]]
name = "标签"
url = "/tags"
weight = 3

[[menu.main]]
name = "关于"
url = "/about"
weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "catppuccin-frappe"
    tabWidth = 4
